/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class GamersClub */

#ifndef _Included_GamersClub
#define _Included_GamersClub
#ifdef __cplusplus
extern "C" {
#endif
#undef GamersClub_FOCUS_TRAVERSABLE_UNKNOWN
#define GamersClub_FOCUS_TRAVERSABLE_UNKNOWN 0L
#undef GamersClub_FOCUS_TRAVERSABLE_DEFAULT
#define GamersClub_FOCUS_TRAVERSABLE_DEFAULT 1L
#undef GamersClub_FOCUS_TRAVERSABLE_SET
#define GamersClub_FOCUS_TRAVERSABLE_SET 2L
#undef GamersClub_TOP_ALIGNMENT
#define GamersClub_TOP_ALIGNMENT 0.0f
#undef GamersClub_CENTER_ALIGNMENT
#define GamersClub_CENTER_ALIGNMENT 0.5f
#undef GamersClub_BOTTOM_ALIGNMENT
#define GamersClub_BOTTOM_ALIGNMENT 1.0f
#undef GamersClub_LEFT_ALIGNMENT
#define GamersClub_LEFT_ALIGNMENT 0.0f
#undef GamersClub_RIGHT_ALIGNMENT
#define GamersClub_RIGHT_ALIGNMENT 1.0f
#undef GamersClub_serialVersionUID
#define GamersClub_serialVersionUID -7644114512714619750i64
#undef GamersClub_serialVersionUID
#define GamersClub_serialVersionUID 4613797578919906343i64
#undef GamersClub_INCLUDE_SELF
#define GamersClub_INCLUDE_SELF 1L
#undef GamersClub_SEARCH_HEAVYWEIGHTS
#define GamersClub_SEARCH_HEAVYWEIGHTS 1L
#undef GamersClub_OPENED
#define GamersClub_OPENED 1L
#undef GamersClub_serialVersionUID
#define GamersClub_serialVersionUID 4497834738069338734i64
#undef GamersClub_DEFAULT_CURSOR
#define GamersClub_DEFAULT_CURSOR 0L
#undef GamersClub_CROSSHAIR_CURSOR
#define GamersClub_CROSSHAIR_CURSOR 1L
#undef GamersClub_TEXT_CURSOR
#define GamersClub_TEXT_CURSOR 2L
#undef GamersClub_WAIT_CURSOR
#define GamersClub_WAIT_CURSOR 3L
#undef GamersClub_SW_RESIZE_CURSOR
#define GamersClub_SW_RESIZE_CURSOR 4L
#undef GamersClub_SE_RESIZE_CURSOR
#define GamersClub_SE_RESIZE_CURSOR 5L
#undef GamersClub_NW_RESIZE_CURSOR
#define GamersClub_NW_RESIZE_CURSOR 6L
#undef GamersClub_NE_RESIZE_CURSOR
#define GamersClub_NE_RESIZE_CURSOR 7L
#undef GamersClub_N_RESIZE_CURSOR
#define GamersClub_N_RESIZE_CURSOR 8L
#undef GamersClub_S_RESIZE_CURSOR
#define GamersClub_S_RESIZE_CURSOR 9L
#undef GamersClub_W_RESIZE_CURSOR
#define GamersClub_W_RESIZE_CURSOR 10L
#undef GamersClub_E_RESIZE_CURSOR
#define GamersClub_E_RESIZE_CURSOR 11L
#undef GamersClub_HAND_CURSOR
#define GamersClub_HAND_CURSOR 12L
#undef GamersClub_MOVE_CURSOR
#define GamersClub_MOVE_CURSOR 13L
#undef GamersClub_NORMAL
#define GamersClub_NORMAL 0L
#undef GamersClub_ICONIFIED
#define GamersClub_ICONIFIED 1L
#undef GamersClub_MAXIMIZED_HORIZ
#define GamersClub_MAXIMIZED_HORIZ 2L
#undef GamersClub_MAXIMIZED_VERT
#define GamersClub_MAXIMIZED_VERT 4L
#undef GamersClub_MAXIMIZED_BOTH
#define GamersClub_MAXIMIZED_BOTH 6L
#undef GamersClub_serialVersionUID
#define GamersClub_serialVersionUID 2673458971256075116i64
#undef GamersClub_EXIT_ON_CLOSE
#define GamersClub_EXIT_ON_CLOSE 3L
#ifdef __cplusplus
}
#endif
#endif
